# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"\"\n\x10RemoveTagRequest\x12\x0e\n\x06tag_id\x18\x01 \x01(\t\"$\n\x11RemoveTagResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32X\n\x0fgRPCPostService\x12\x45\n\x12RemoveTagFromPosts\x12\x16.post.RemoveTagRequest\x1a\x17.post.RemoveTagResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOVETAGREQUEST']._serialized_start=20
  _globals['_REMOVETAGREQUEST']._serialized_end=54
  _globals['_REMOVETAGRESPONSE']._serialized_start=56
  _globals['_REMOVETAGRESPONSE']._serialized_end=92
  _globals['_GRPCPOSTSERVICE']._serialized_start=94
  _globals['_GRPCPOSTSERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
